version: '3.8'
services:
  db:
    image: postgres:15
    container_name: rag-chat-db
    environment:
      POSTGRES_DB: rag_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  api:
    build: .
    container_name: rag-chat-api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: always
volumes:
  pgdata: